version: '3.8'

services:
  # MySQL Database
  mysql:
    image: mysql:8.0
    container_name: group_scheduler_db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword123
      MYSQL_DATABASE: scheduler_db
      MYSQL_USER: scheduler_user
      MYSQL_PASSWORD: scheduler_pass123
    ports:
      - "3307:3306"  # Use 3307 to avoid conflicts with local MySQL
    volumes:
      - mysql_data:/var/lib/mysql
      - ./backend/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  # Backend FastAPI
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: group_scheduler_backend
    env_file:
      - ./backend/.env
    environment:
      DB_HOST: mysql
      DB_PORT: 3306
      DB_USER: scheduler_user
      DB_PASSWORD: scheduler_pass123
      DB_NAME: scheduler_db
      SECRET_KEY: ${SECRET_KEY:-your-secret-key-here}
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}
      GOOGLE_REDIRECT_URI: http://localhost:8000/auth/google/callback
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    depends_on:
      mysql:
        condition: service_healthy
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload

  # Frontend React
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: group_scheduler_frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules  # Prevent node_modules from being overwritten
    environment:
      - REACT_APP_API_URL=http://localhost:8000
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
    depends_on:
      - backend
    stdin_open: true  # Needed for React hot reload
    tty: true

volumes:
  mysql_data: